### ISSUE TITLE
quickstart-qemu.md: non matched device type

### ISSUE THREAD

**Issue by perezmeyer** [balena-os/leviathan#1036]
The example config uses ```deviceType: 'genericx86-64-ext'``` while later on the text says "Here, we are assuming that the device under test (DUT) is a raspberrypi3."

**Comment by vipulgupta2048** [comment]
Thanks for reporting this, I understand the confusion. This is not present in the latest docs committed to master: https://github.com/balena-os/leviathan/blob/master/documentation/quickstart-qemu.md 

This line and more improvements were made in recent changes which seems to be getting published on our online GH docs here:  https://balena-os.github.io/leviathan

I will investigate and update when the latest docs have been published

**Comment by perezmeyer** [comment]
Closed with https://github.com/balena-os/leviathan/pull/1039
