### ISSUE TITLE
Check integrity of Images on upload

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-os/leviathan#356]
Got some feedback to work on improving testbot from the 3rd Sept Release Party 

Current workflow --> flaky uploads of OS image leads to image corruption --> An corrupted os image is then flashed and used in the device to flash and wait for it to come online and eventually fails --> Which leads to time taking flaky tests.

Integrating an OS image integrity check `beforeFlash` would really be time-saving. 
cc: @roman-mazur

**Comment by roman-mazur** [comment]
Quick thoughts: we can modify the core to return a fingerprint of the image once the upload is done. If the client detects the mismatch, it retries the upload.

**Comment by vipulgupta2048** [comment]
Exactly what I was thinking, that way we start another upload way faster. 
I will get started right on that :+1:

**Comment by vipulgupta2048** [comment]
@rcooke-warwick We should try this again one more time as well :joy:

**Comment by vipulgupta2048** [comment]
@rcooke-warwick Do we check for integrity now, the last time we looked into Zlibs?

**Comment by vipulgupta2048** [comment]
No longer required, check current mechanism for upload #567
