### ISSUE TITLE
Consider reducing number of iterations of utils.waitUntil() helper function

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-os/leviathan#404]
https://github.com/balena-os/leviathan/blob/f016599b56d7b696a3427c6be14e4d57f091fa2a/core/lib/common/utils.js#L85-L90

**Comment by rcooke-warwick** [comment]
it is configurable: 

```js
waitUntil: async (
		promise,
		rejectionFail = true,
		_times = 20,
		_delay = 30000,)
		
	But reducing the default is a good idea potentially 

```

**Comment by vipulgupta2048** [comment]
Yes, atm Supervisor calls that I make to check for Device trees test might go on for 20 times and eventually timeout. I think we can discuss either reducing iterations or timeout or both to get faster outcomes. But, since this is a helper we might need to consider every scenario its being used.

**Comment by rcooke-warwick** [comment]
```js
waitUntil(async() => { 
    function
},true, 5, 30000)
 ```

^ you can do this to choose 5 iterations

Does node support named arguements btw? It would make it easier to configure funcitons like these
