### ISSUE TITLE
Can we get batched jobs done with Leviathan/Jenkins

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-os/leviathan#509]
Do a test job X times, can we do it through Jenkins and not locally.

**Comment by vipulgupta2048** [comment]
@klutchell Thought about it as I was thinking about #508 
The challenge/issue is not running the tests multiple times or on multiple workers. The challenge is how do we deliver the assets. For a Jenkins job like that, how does one upload the assets to run the test suites? Here's what I was thinking. 

(balenaOS image, suites, config.json) - Can't be uploaded, either the image comes from an upstream job or they fetch it with fetchOS helper right in the tests. I like the former option since that way folks can run a meta-balena job for their PR branch with custom tests, and the balenaOS image gets generated. Problem solved. 

In the downstream, leviathan jobs we add logic to repeat tests on the basis of a variable in Jenkins that can be configured using the Jenkins "Build with parameters" job. We would also need to tell this special job about where to find the balenaOS artifacts built using the PR branch. Since we shouldn't be interfering with the PR flow anyway. We can do a test job X times for only one device type though.

**Comment by klutchell** [comment]
> Can't be uploaded, either the image comes from an upstream job or they fetch it with fetchOS helper right in the tests. I like the former option since that way folks can run a meta-balena job for their PR branch with custom tests, and the balenaOS image gets generated. Problem solved.

The only issue I see here is that meta-balena jobs and their artifacts are only kept around for a few days (I think).

What if we run the yocto-<device-type> job first, then execute the leviathan job x times per the parameters. That way if artifacts have been purged from your last meta-balena run new ones will be generated for you but only for the device you're testing?

This is getting messy though, maybe we need to rethink this.

**Comment by vipulgupta2048** [comment]
Quite frankly, I don't think it's gonna remain as automated as we think this is going to be if we do this with Jenkins. Maybe discussing this async might not be the best step. My alternative was,

We tweak Leviathan to run the tests X number of times over on local testing/development rig instead. How about we do a call after I come back to figure out development testing?

**Comment by klutchell** [comment]
Yeah, we need to take this to another call with Ryan and Alex G I think. Maybe even an arch call.

**Comment by rcooke-warwick** [comment]
This no longer feels relevent, based on the improvement introduced here: https://github.com/balena-os/leviathan/pull/809 

tests can be marked as unstable: https://github.com/balena-os/leviathan/pull/809
