### ISSUE TITLE
`workers.balenaApplication` should accept a slug

### ISSUE THREAD

**Issue by klutchell** [balena-os/leviathan#576]
Currently it defaults to `testbot-rig` for Jenkins builds but if we change it to a proper slug it fails.

https://github.com/balena-os/leviathan/blob/50317909743fbe39c0e2a99bc1b8b3c8f3d420a8/client/lib/balena.ts#L56-L72

```
[2021-12-15T19:32:25.963Z] INFO: ERROR ENCOUNTERED: Application not found: balena/testbot-rig. 
```

This is odd because the SDK claims to support slugs in this function:
- https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.device.tags.getAllByApplication

**Comment by vipulgupta2048** [comment]
@klutchell With the update of the SDK version, I think this would get resolved. Do link the ongoing SDK update PR if you think it does?
