### ISSUE TITLE
Solve the inital fail that leads to false positive

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-os/leviathan#610]
https://github.com/balena-os/meta-balena/pull/2478 tests are leading to a false positive condition that can be resolved by outputting an error message here. Creating an issue so I don't forget. 

https://github.com/balena-os/leviathan/blob/810434b46e3d25ba16c074e97d15c33c1bcce49b/core/lib/main.js#L277-L279

**Comment by rcooke-warwick** [comment]
I think https://github.com/balena-os/leviathan/pull/463 removes the false positive iirc

**Comment by vipulgupta2048** [comment]
The suite Subprocess PR will make these handlers obsolete and hence removes the chance of a false positive occurring again.

**Comment by jakogut** [comment]
@vipulgupta2048 I'm not sure it does, the code should work basically identically to how it does now.

**Comment by vipulgupta2048** [comment]
Should have removed this link after @jakogut's comment. This problem still is present.
