### ISSUE TITLE
Documentation and examples refer to obsolete env vars

### ISSUE THREAD

**Issue by lmbarros** [balena-os/leviathan#617]
Both the documentation and `config.example.js` refer to environment variables that appear to be obsolete:

* `BALENA_CLOUD_API_KEY` and `BALENACLOUD_API_KEY`: Those appear to have been superseded by `BALENA_API_KEY`.
* `BALENACLOUD_ORG`: Maybe this one was completely removed? It doesn't seem to appear anywhere in the code anymore.

**Comment by vipulgupta2048** [comment]
@lmbarros The environment variables used by the documentation are just for reference. They can be of any name and are basically placeholders for the values. They don't hold any significance to the code. Most users I have seen use values in plain text for their config.js and don't choose to create env variables 

Did it cause confusion for you as you thought these env variables should be exactly what the documentation says? 

After our conversation, I had a chance to look into this and the worker code referencing `BALENA_API_KEY` is referring to the environment variable set in the worker container for the balena Device key when your turn on the API docker label and the device API keys gets added to the device.
