### ISSUE TITLE
Improve docs for QEMU worker

### ISSUE THREAD

**Issue by lmbarros** [balena-os/leviathan#618]
Maybe the introduction of QEMU workers is a feature large enough to justify restructuring the docs a bit more deeply. For example, *maybe* it would be worth to have two separate "quick starts", one for QEMU, another one for testbot.

Anyway, here's a list of more specific improvements I can think of:

* [x] The `README` says that we shall run `make local` to run tests using a QEMU worker. This should be `make local-test` now, AFAIU. Also, should probably be mentioned in the quick start, too (or instead).
* [x] The quick start guide says that "as a prerequisite for this guide, you will have to prepare your testbot". This is no longer true with QEMU workers.
* [x] Would be very nice to have a `config.json` example for QEMU that just works out of the box (maybe using the e2e tests).
* [x] Document how `networkWired` and `networkWireless` interact with QEMU workers.

**Comment by jakogut** [comment]
For the last part, the `networkWired` and `networkWireless` don't interact with the QEMU worker at all.

**Comment by vipulgupta2048** [comment]
I agree
