### ISSUE TITLE
Docs: Lean More Doc Links are Private

### ISSUE THREAD

**Issue by keenanjohnson** [balena-os/leviathan#738]
Hello!

I tried to follow the Google drive links in [documentation/learn-more.md](https://github.com/balena-os/leviathan/blob/master/documentation/learn-more.md), but each of the google drive links was listed as private, and I wasn't able to access them.

**Comment by keenanjohnson** [comment]
Oh I see. I was just reading the repo and was curious and thought this to be a bug more than an intended idea.

**Comment by vipulgupta2048** [comment]
Right on, @keenanjohnson I will update this issue as we release more information about the product. For now, if you like to take Leviathan for a spin, you can follow this guide: https://balena-os.github.io/leviathan/pages/Getting-Started/quickstart/quickstart-qemu.html

Let us know how it goes. Closing this issue.
