### ISSUE TITLE
improve getting started instructions and add tips 

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-os/leviathan#840]
based on the onboarding of Zahari with the leviathan framework (qemu worker)

- document the env variables
- document how to access the DUT over ssh (or maybe we can include a script in the core/worker container so you can just run the - script and get a connection to the device)
- the docker setup requirements should be clear (post-install instructions to add user to docker group)
- instructions to load tun module (can we automate this in the dockerfile?)
- how to run just one test - for now just clarifying that you can comment out the non needed ones might be enough

**Comment by vipulgupta2048** [comment]
Hey @alexgg can you give an example of the env file you use for your tests?
