### ISSUE TITLE
[ssh] cloud suite failure for all device types in jenkins

### ISSUE THREAD

**Issue by acostach** [balena-os/leviathan#844]
The cloud test suite fails for all devices when run in Jenkins, but not locally - as mentioned in internal thread https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/.E2.9C.94.20v2.2E105.2E24/near/310139696

Example PR:
https://github.com/balena-os/balena-raspberrypi/pull/936

**Comment by rcooke-warwick** [comment]
resolved by https://github.com/balena-os/meta-balena/pull/2870
